button_signin = '//*[@id="main-menu"]/ul/li[2]/a/span'
field_login = '/html/body/div[3]/div[1]/div[1]/form/table/tbody/tr[1]/td[2]/input'
field_password = '/html/body/div[3]/div[1]/div[1]/form/table/tbody/tr[2]/td[2]/input'
button_auth = '/html/body/div[3]/div[1]/div[1]/form/table/tbody/tr[3]/td[2]/input'
button_add_user = '/html/body/div[3]/p[1]/a'
button_submit_form_user = '/html/body/div[3]/form/table/tbody/tr[21]/td[2]/input'
account_button = '//*[@id="fat-menu"]/a'
exit_button = '//*[@id="fat-menu"]/ul/li[3]/a'
search_user_field = '/html/body/div[3]/form/table/tbody/tr[4]/td/input'
table_user_data = '/html/body/div[3]/div[1]/div/div[2]/table'
button_user_list = '//*[@id="main-menu"]/ul/li[1]/a/span'
search_user_button = '/html/body/div[3]/form/table/tbody/tr[5]/td[1]/button'
view_user_button = '/html/body/div[3]/table/tbody/tr/td[7]/a'
delete_user_button = '/html/body/div[3]/table/tbody/tr/td[6]/a'

fathername_field = '/html/body/div[3]/form/table/tbody/tr[11]/td[2]/input[1]'